module.exports = {
  ADD_DOCUMENT: 'ADD_DOCUMENT',
  UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
  CHANGE_CURRENT_DOCUMENT: 'CHANGE_CURRENT_DOCUMENT',
  OPEN_DOCUMENT: 'OPEN_DOCUMENT',
  UPDATE_CONFIG: 'UPDATE_CONFIG',
  LOAD_CONFIG: 'LOAD_CONFIG',
  LOAD_DOCS: 'LOAD_DOCS'
}